name: Jekyll site CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: |
          gem install bundler jekyll
          bundle init
          echo 'gem "jekyll-paginate"' >> Gemfile
          echo 'gem "jekyll-sitemap"' >> Gemfile
          echo 'gem "kramdown-parser-gfm"' >> Gemfile
          echo 'gem "beautiful-jekyll-theme", git: "https://github.com/daattali/beautiful-jekyll.git"' >> Gemfile
          bundle install

      - name: Build site
        run: bundle exec jekyll build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
